### ISSUE TITLE
extobj.cfg Mount

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#10]
object mount does not match scripts

**Comment by Admin-Yukiko** [comment]
More information is needed. What object? Which mount?

**Comment by andrtechno** [comment]
well, for example
chrdeath.src > function dismount

**Comment by DavidJSGardner** [comment]
Issue fixed with commit [0fe4b29](https://github.com/polserver/ClassicDistro/commit/0fe4b293cdd08998eb87d58e998ea83afb69a396)
