### ISSUE TITLE
vendor train <skill>

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#15]
not work

**Comment by Admin-Yukiko** [comment]
I think I have this fixed. I am going to have ThisIsMe review my code. If it passes his review, I will commit the change. Normally I would just commit without a review but my fix is a simplification of the original code. I want to be certain that my simple fix is ok.

**Comment by Admin-Yukiko** [comment]
Fixed this issue. Thanks to ThisIsMe for his help.

**Comment by andrtechno** [comment]
@Admin-Yukiko 
nothing has changed, I throw 100 gp at the NPC, writes Your skill increases.

**Comment by andrtechno** [comment]
there is a feeling that here is a problem it comes to here until the skill does not give

SetAttributeBaseValue(who, attributeid, new_level);
DoRecalcVitals(who);

**Comment by Admin-Yukiko** [comment]
I will do some more testing. Can you tell me what skill you are trying to train? What type of vendor you are asking to train your skill? what is the level of the skill you want to train?

**Comment by andrtechno** [comment]
Yes, anyone does not want, asks for 100gp, I throw 100gp at him. he takes them but skill does not give

**Comment by andrtechno** [comment]
learning by example
npcdesc.cfg
NpcTemplate mage


And yes, events do not work for me (EVID_SPEECH) and any EVID_*
I changed them to SYSEVENT_SPEECH

EVID_SPEECH "vendor train" and other text commands didn't work for me at all with this event
you should also check all these events EVID_*

**Comment by Admin-Yukiko** [comment]
I believe ThisIsMe fixed this. He rewrote a lot of the code and tested it. So it should be working now.
