### ISSUE TITLE
housedeed.src

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#20]
```
if(!CanBuildHere(who)&& !who.cmdlevel)
    SendSysMessage(who, "You are not authorized to build a house here.", color := 33);
    return 0;
endif
```

CanBuildHere() - uses a cfg file that doesn't exist (::buildlocs)

**Comment by Admin-Yukiko** [comment]
Oops! You can either remove that check for a valid location or if you want to prevent building only in certain areas, use the following format for your valid locations file. I will fix the houseDeed script by commenting out that "if" clause.
`region Anya
{
rect 332 1375 515 1533
}

region Tremaine
{
rect 3835 3649 3996 3757
}

region Anarielle
{
4722 3151 4984 3371
}
`

**Comment by andrtechno** [comment]
yes I did, for commenting

**Comment by andrtechno** [comment]
I see you already got tickets))) but I would like the assembly to be more reliable
