### ISSUE TITLE
.spawner

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#8]
select realm > britania
region list > select any region
click to "group settings"

Add/Del - Delete not work
Enabled - Disabled not work
Press "Apply"
use cmd ".savenow" or any save
After save world reload pol.exe 

change not saved

**Comment by Admin-Yukiko** [comment]
I tested it and it worked. It is a bit tricky to use. I am attaching a ZIP file with documentation for the SpawnSystem. The gumps pictured in the docs have some visual improvements but the usage is the same as the Classic Distro version
[Spawner_docs.zip](https://github.com/polserver/ClassicDistro/files/8378100/Spawner_docs.zip)
.
